name = "ATLabDataVisualization"
uuid = "2ed60681-16cb-4ea5-9407-fb9a9f9233f7"
version = "1.0.0-DEV"
authors = ["Thomas Vandamme"]

[deps]
ATLabData = "2001816d-1027-44d7-a455-52de789fd3bf"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
Integrals = "de52edbc-65ea-441a-8357-d3a637375a31"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[sources]
ATLabData = {rev = "main", url = "https://github.com/hadschy/ATLabData"}

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
